### ISSUE TITLE
Logo for galleroid

### ISSUE THREAD

**Issue by zuurw** [brickers/galleroid#6]
HI Im a Graphic Designer that likes to contribute to open source projects and also a Polaroid entushiast, so it would be a pleasure to work with you in this project, if you need a logo I will do it for you.

Best regards.

**Comment by zuurw** [comment]
Hello @brickers  , Im going to close this issue, if you need my help with the logo you can reopen.
Best Regards.

**Comment by brickers** [comment]
hi zuurw. sorry not to see your offer sooner - that's very kind of you to offer and I would be very happy for you to make a logo for galleroid - thank you

**Comment by zuurw** [comment]
Hi @brickers, do you have something in your mind for the logo? any request?

Regards!

**Comment by brickers** [comment]
i don't really have any specific ideas - the name galleroid is a combination of gallery and polaroid, so whatever you can think of to join those two ideas together would be good. I do like very simple, iconic logos too. I hope that's useful?

**Comment by zuurw** [comment]
Hi @brickers here are the degins that I create for Galleroid, I hope you like it.

LOGO CONCEPT
For the logo concept I was inspired by the pollaroid camera, a file folder and a snapshot photo. So first I created the file folder and extended the bottum and created the camera pollaroid, then added the photos snapshot and a pointing finger as if you were choosing the photos in the gallery.

Regards!

![gelleroid proposal](https://user-images.githubusercontent.com/40801473/42935264-20e9c36c-8b41-11e8-8673-688b1e7eff4b.png)

**Comment by zuurw** [comment]
Hi, @brickers did you like any of the logos that I design?

Best Regards!

**Comment by brickers** [comment]
hi zuurw. I'm sorry, i'm afraid they're not really to my taste. i had a look at your other logos and i really liked them, particularly the ones where a shape is made out of parallel lines such as NavyPlayer and Parrot. I wonder whether a simple camera or polaroid shape made out of lines would be possible?

**Comment by zuurw** [comment]
Hi @brickers, no problem, I can do that I will do want you want.

Best Regards!

**Comment by zuurw** [comment]
Hi @brickers, I create this design, see if this what you were talking about.

![gelleroid proposal2](https://user-images.githubusercontent.com/40801473/43106600-39a5a9a0-8ed1-11e8-8785-e848f20d7624.png)

**Comment by brickers** [comment]
hey zuurw, these are really great - thank you very much. if i choose one from these, will you be able to do one more revision? the reason being that at small sizes the lines make the logo look unclear, so I think thicker lines would look better. currently there are 16 lines - would it be possible to do the logo with 8 lines? would it be possible for all the ends of the lines to be rounded too?

i know I'm asking a lot, and that you are doing this for free and have already done two versions, so i do understand if you are unable to do any more - just let me know. thanks

**Comment by brickers** [comment]
by the way, the one i like is the left hand one on the third row - the one with mostly gray lines, coloured lines under the circle and black writing

**Comment by zuurw** [comment]
Hi @brickers I made the changes and create some variations of the logo.
see if this what you want?

![logo proposal polaroid4](https://user-images.githubusercontent.com/40801473/43128406-d87a62c0-8f29-11e8-9cac-6d6510b08e4b.png)

**Comment by brickers** [comment]
Hi zuurw. I like the middle two - are they different from each other?

**Comment by zuurw** [comment]
Hi @brickers, now that I notice that the 2# and 3# in both rows are the same, only the 1# are different :)
When I finish I didnt like very much the results of the two 1st, than I add the gray circle in the middle and I think it looks much better and works better also in small sizes, did you try in small sizes?

So if you want I can make the PR with the logo files.

Best Regards!

**Comment by brickers** [comment]
Yes I did have a look at small sizes and they look great. Please do a pull request for the middle one with the gray circle and thanks very much for your time and efforts

**Comment by zuurw** [comment]
Hi I create the pull request and put also the logo on the README text, I hope everything it´s ok with the files, if not just say it.

Do you need something more? 

Best Regards!

**Comment by zuurw** [comment]
Hello @brickers, do you still want this logo? I create the PR but you didnt merged it.

Best Regards!

**Comment by brickers** [comment]
amazing work, zuurw. thanks for all your work, I really think the landing page looks good with the new logo. I will update the test page with the logo too soon!

**Comment by zuurw** [comment]
Hi @brickers, I made a new PR with  all the files of the logo and logotype, with colors and with black and white versions, I send PNG and SVG files of all the files.

Best Regards.
