### ISSUE TITLE
Active thumbnails on top

### ISSUE THREAD

**Issue by githubchicken** [brickers/galleroid#9]
I noticed active "thumbnails" show on top of fullscreen pics. Tested only on Safari & Firefox on my iphone 8. Screenshots attached. 
![image1](https://user-images.githubusercontent.com/46612016/51062484-a8b54e00-15bc-11e9-8e71-8a1ffcfa77ef.jpg)
![image2](https://user-images.githubusercontent.com/46612016/51062485-a8b54e00-15bc-11e9-8fe6-41b68a97f115.jpg)

Doesn't seem to happen on linux firefox desktop. Great image viewer. Thanks!

**Comment by brickers** [comment]
Thanks for using and for providing feedback. I’ve seen this issue before and thought it was fixed, so I’ll take a look tomorrow and see what I can do. Cheers

**Comment by brickers** [comment]
I removed that background colour a little while ago and the layout in the first picture is not how it should currently display on a mobile, so I'm just wondering if you're using the most recent version of galleroid?

**Comment by brickers** [comment]
Thanks Matt, really nice to hear of someone using it. Do you mind if I see it in action on your site? not sure if you can reply if I close the issue, so feel free to close, otherwise I will if I don't hear from you 

thanks
